language: node_js
node_js:
  - "node"
install:
  - yarn
script:
  yarn build
after_success:
  - git config --global user.email "admin@zhangzisu.cn"
  - git config --global user.name "ZhangZisu"
  - git clone -b gh-pages https://$TOKEN@github.com/ZhangZisu/perilla publish
  - rm -rf publish/*
  - cp -r dist/* publish
  - cd publish
  - echo "perilla.js.org" > CNAME
  - git add .
  - git commit -m 'Travis Build'
  - git push -u origin gh-pages
branches:
  only:
    - master    - /^greenkeeper/.*$/
cache:
  yarn: true