osx_image: xcode8.3

os:
  - linux
  - osx

language: node_js
node_js:
  - "node"
install:
  - yarn
script:
  - yarn electron:publish

branches:
  only:
    - master
    - /^greenkeeper/.*$/
cache:
  yarn: true