branches:
  only:
    - master

image: Visual Studio 2017
platform:
  - x64

cache:
  - node_modules
  - '%APPDATA%\npm-cache'
  - '%USERPROFILE%\.electron'
  - '%USERPROFILE%\AppData\Local\Yarn\cache'

init:
  - git config --global core.autocrlf input

install:
  - ps: Install-Product node ''
  - git reset --hard HEAD
  - yarn

build_script:
  - yarn build
  - yarn electron:publish

after_build:
  - git config --global user.email "admin@zhangzisu.cn"
  - git config --global user.name "ZhangZisu"
  - git clone -b gh-pages https://$GH_TOKEN@github.com/ZhangZisu/perilla publish
  - rm -rf publish/*
  - cp -r dist/* publish
  - cd publish
  - echo "perilla.js.org" > CNAME
  - git add .
  - git commit -m 'AppVeyor Build'
  - git push -u origin gh-pages

test: off
