version: 2
jobs:
  build:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - run: sudo npm install -g npm
      - run: sudo npm install -g yarn
      - run: yarn
      - run: yarn build
      - run: git config --global user.email "admin@zhangzisu.cn"
      - run: git config --global user.name "ZhangZisu"
      - run: sh gh-pages.sh
